version: '3'

volumes:
  mysql_local_data: {}
  mysql_local_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: openapi_documentor_local_django
    container_name: django
    depends_on:
      - mysql
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    command: /start

  mysql:
    image: mariadb:latest
    volumes:
      - ./data/mysql:/var/lib/mysql:z
      - mysql_local_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.mysql
      - .env
