version: '3'

volumes:
  mysql_data: {}
  mysql_data_backups: {}
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: openapi_documentor:1.0
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    command: /start
  
  mysql:
    image: mariadb:latest
    volumes:
      - mysql_data:/var/lib/mysql/data:Z
      - mysql_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.mysql

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: openapi_documentor_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:5.0

  
  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - mysql_data_backups:/backups:z
