# Generated by Django 3.1.7 on 2021-03-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='formatted',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
