# Generated by Django 3.1.7 on 2021-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0002_document_formatted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
