#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

# /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --forwarded_allow_ips='*'
/usr/local/bin/gunicorn --forwarded-allow-ips="*" config.wsgi --bind 0.0.0.0:5000 --chdir=/app
